# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000023ltoo1\tmp\build\80754af9\rsync-recipes\conda-4.6.14-python_2.7-on-winbuilder, last modified Wed Apr 17 13:34:54 2019
# ------------------------------------------------

package:
    name: conda
    version: 4.6.14
source:
    fn: conda-4.6.14.tar.gz
    sha256: 6e65665406e29256c96199ed17b767c0a3ab449df60d09d3185dbf9c30bb2d45
    url: https://github.com/conda/conda/archive/4.6.14.tar.gz
build:
    always_include_files:
        - Scripts/activate
        - Scripts/activate.bat
        - Scripts/deactivate
    number: '0'
    string: py27_0
requirements:
    build:
        - m2-base 1.0.0 3
        - m2-bash 4.3.042 5
        - m2-bash-completion 2.3 2
        - m2-catgets 1.1 3
        - m2-coreutils 8.25 102
        - m2-dash 0.5.8 2
        - m2-file 5.25 2
        - m2-filesystem 2016.04 4
        - m2-findutils 4.6.0 2
        - m2-gawk 4.1.3 2
        - m2-gcc-libs 5.3.0 4
        - m2-gettext 0.19.7 4
        - m2-gmp 6.1.0 3
        - m2-grep 2.22 4
        - m2-gzip 1.7 2
        - m2-inetutils 1.9.2 2
        - m2-info 6.0 2
        - m2-less 481 2
        - m2-libasprintf 0.19.7 4
        - m2-libcatgets 1.1 3
        - m2-libcrypt 1.3 2
        - m2-libgettextpo 0.19.7 4
        - m2-libiconv 1.14 3
        - m2-libintl 0.19.7 4
        - m2-liblzma 5.2.2 2
        - m2-libpcre 8.38 2
        - m2-libreadline 6.3.008 8
        - m2-libutil-linux 2.26.2 2
        - m2-libxml2 2.9.2 3
        - m2-mintty 1!2.2.3 2
        - m2-mpfr 3.1.4 2
        - m2-msys2-launcher-git 0.3.28.860c495 2
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-ncurses 6.0.20160220 2
        - m2-sed 4.2.2 3
        - m2-tftp-hpa 5.2 2
        - m2-time 1.7 2
        - m2-ttyrec 1.0.8 2
        - m2-tzcode 2015.e 2
        - m2-util-linux 2.26.2 2
        - m2-which 2.21 3
        - m2-zlib 1.2.8 4
        - msys2-conda-epoch 20160418 1
    host:
        - certifi 2019.3.9 py27_0
        - enum34 1.1.6 py27_1
        - futures 3.2.0 py27_0
        - menuinst 1.4.16 py27h0c8e037_0
        - pip 19.0.3 py27_0
        - python 2.7.16 hcb6e200_0
        - pywin32 223 py27h0c8e037_1
        - ruamel_yaml 0.15.46 py27h0c8e037_0
        - setuptools 41.0.0 py27_0
        - sqlite 3.27.2 h0c8e037_0
        - vc 9 h7299396_1
        - vs2008_runtime 9.00.30729.1 hfaea7d5_1
        - wheel 0.33.1 py27_0
        - wincertstore 0.2 py27hf04cefb_0
        - yaml 0.1.7 h3e6d941_2
    run:
        - enum34
        - futures >=3.0.0
        - menuinst >=1.4.11,<2
        - pycosat >=0.6.3
        - pyopenssl >=16.2.0
        - python >=2.7,<2.8.0a0
        - requests >=2.18.4,<3
        - ruamel_yaml >=0.11.14,<0.16
        - setuptools >=31.0.1
    run_constrained:
        - conda-build >=3
        - conda-env >=2.6
        - cytoolz >=0.8.1
        - setuptools >=31.0.1
test:
    files:
        - test_conda.bat
    imports:
        - conda
        - conda_env
    requires:
        - m2-base
        - m2-bash
        - m2-filesystem
        - mock
        - pexpect
        - pytest
        - responses
    source_files:
        - conftest.py
        - setup.cfg
        - tests
about:
    description: 'Conda is an open source package management system and environment
        management system for installing multiple versions of software packages and
        their dependencies and switching easily between them. It works on Linux, OS
        X and Windows, and was created for Python programs but can package and distribute
        any software.

        '
    dev_url: https://github.com/conda/conda
    doc_url: https://conda.io/projects/conda/en/latest/
    home: https://conda.io
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: OS-agnostic, system-level binary package and environment manager.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - kalefranz
        - mbargull
        - mcg1969
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
