# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003ngfip2\tmp\build\80754af9\rsync-recipes\win_inet_pton-1.1.0-python_2.7-on-winbuilder, last modified Mon Feb 25 15:14:44 2019
# ------------------------------------------------

package:
    name: win_inet_pton
    version: 1.1.0
source:
    sha256: dd03d942c0d3e2b1cf8bab511844546dfa5f74cb61b241699fa379ad707dea4f
    url: https://pypi.io/packages/source/w/win_inet_pton/win_inet_pton-1.1.0.tar.gz
build:
    number: '0'
    script: C:\ci\win_inet_pton_1551195527708\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py27_0
requirements:
    host:
        - certifi 2018.11.29 py27_0
        - pip 19.0.1 py27_0
        - python 2.7.15 hcb6e200_15
        - setuptools 40.8.0 py27_0
        - sqlite 3.26.0 h0c8e037_0
        - vc 9 h7299396_1
        - vs2008_runtime 9.00.30729.1 hfaea7d5_1
        - wheel 0.32.3 py27_0
        - wincertstore 0.2 py27hf04cefb_0
    run:
        - python >=2.7,<2.8.0a0
test:
    imports:
        - win_inet_pton
about:
    dev_url: https://github.com/hickeroar/win_inet_pton
    home: https://github.com/hickeroar/win_inet_pton
    license: PUBLIC-DOMAIN
    license_file: LICENSE
    summary: Native inet_pton and inet_ntop implementation for Python on Windows (with
        ctypes).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pmlandwehr
