# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\ci\containers\00001srkti9\tmp\build\80754af9\rsync-recipes\pycparser-2.19-python_2.7-on-winbuilder, last modified Sun Sep 30 10:17:06 2018
# ------------------------------------------------

package:
    name: pycparser
    version: '2.19'
source:
    fn: pycparser-2.19.tar.gz
    sha256: a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3
    url: https://pypi.io/packages/source/p/pycparser/pycparser-2.19.tar.gz
build:
    noarch: false
    number: '0'
    script: C:\ci\pycparser_1538320863152\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py27_0
requirements:
    host:
        - certifi 2018.8.24 py27_1
        - pip 10.0.1 py27_0
        - python 2.7.15 he216670_0
        - setuptools 40.2.0 py27_0
        - vc 9 h7299396_1
        - vs2008_runtime 9.00.30729.1 hfaea7d5_1
        - wheel 0.31.1 py27_0
        - wincertstore 0.2 py27hf04cefb_0
    run:
        - python >=2.7,<2.8.0a0
test:
    imports:
        - pycparser
        - pycparser.ply
about:
    description: 'pycparser is a complete parser of the C language, written in pure
        Python

        using the PLY parsing library.  It parses C code into an AST and can serve

        as a front-end for C compilers or analysis tools.

        '
    dev_url: https://github.com/eliben/pycparser
    doc_source_url: https://github.com/eliben/pycparser
    doc_url: https://pypi.python.org/pypi/pycparser
    home: https://github.com/eliben/pycparser
    license: BSD 3-clause
    license_family: BSD
    license_file: LICENSE
    summary: Complete C99 parser in pure Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - synapticarbors
