# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00000pdpakh\tmp\build\80754af9\rsync-recipes\cffi-1.12.2-c_compiler_vs2008-python_2.7-on-winbuilder, last modified Mon Mar 11 10:56:19 2019
# ------------------------------------------------

package:
    name: cffi
    version: 1.12.2
source:
    patches:
        - 0001-Link-to-dl-library.patch
    sha256: e113878a446c6228669144ae8a56e268c91b7f1fafae927adc4879d9849e0ea7
    url: https://pypi.io/packages/source/c/cffi/cffi-1.12.2.tar.gz
build:
    number: '1'
    script: C:\ci\cffi_1552321926499\_h_env\python.exe -m pip install . --no-deps
        -vv
    string: py27hcfb25f9_1
requirements:
    build:
        - vs2008_win-64 9.00.30729.1 hb7fc0b5_1
    host:
        - certifi 2018.11.29 py27_0
        - pip 19.0.3 py27_0
        - pycparser 2.19 py27_0
        - python 2.7.15 hcb6e200_15
        - setuptools 40.8.0 py27_0
        - sqlite 3.26.0 h0c8e037_0
        - vc 9 h7299396_1
        - vs2008_runtime 9.00.30729.1 hfaea7d5_1
        - wheel 0.33.1 py27_0
        - wincertstore 0.2 py27hf04cefb_0
    run:
        - pycparser
        - python >=2.7,<2.8.0a0
        - vc 9.*
test:
    imports:
        - _cffi_backend
        - cffi
    requires:
        - openssl
about:
    description: 'Cffi aims to allow users to call C code from Python without having
        to

        learn a 3rd language. It provides a convenient and reliable way to call

        compiled C code from Python using interface declarations written in C.

        '
    dev_url: https://bitbucket.org/cffi/cffi/overview
    doc_source_url: https://bitbucket.org/cffi/cffi/src/default/doc/?at=default
    doc_url: http://cffi.readthedocs.org
    home: https://bitbucket.org/cffi/cffi
    license: MIT
    license_file: LICENSE
    summary: Foreign Function Interface for Python calling C code.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - inducer
        - mingwandroid
        - ocefpaf
