# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001iiotau\tmp\build\80754af9\rsync-recipes\ca-certificates-2019.1.23-on-winbuilder, last modified Wed Feb  6 09:16:30 2019
# ------------------------------------------------

package:
    name: ca-certificates
    version: 2019.1.23
source:
    fn: cacert.pem
    sha256: c1fd9b235896b1094ee97bfb7e042f93530b5e300781f59b45edf84ee8c75000
    url: https://curl.haxx.se/ca/cacert-2019-01-23.pem
build:
    commands:
        - /usr/bin/curl --cacert %LIBRARY_PREFIX%\\ssl\\cacert.pem https://www.google.com
        - if not exist %LIBRARY_PREFIX%\\ssl\\cacert.pem exit 1
        - if not exist %LIBRARY_PREFIX%\\ssl\\cert.pem exit 1
    string: '0'
about:
    home: https://github.com/conda-forge/ca-certificates-feedstock
    license: ISC
    summary: Certificates for use with other packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
