# This file created by conda-build 3.16.3
# meta.yaml template originally from:
# C:\ci\containers\00001ehk9ga\tmp\build\80754af9\rsync-recipes\requests-2.21.0-python_2.7-on-winbuilder, last modified Mon Dec 17 12:09:48 2018
# ------------------------------------------------

package:
    name: requests
    version: 2.21.0
source:
    sha256: 502a824f31acdacb3a35b6690b5fbf0bc41d63a24a45c4004352b0242707598e
    url: https://pypi.io/packages/source/r/requests/requests-2.21.0.tar.gz
build:
    number: '0'
    script: C:\ci\requests_1545070455850\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed -vv
    string: py27_0
requirements:
    host:
        - certifi 2018.11.29 py27_0
        - pip 18.1 py27_0
        - python 2.7.15 hcb6e200_5
        - setuptools 40.6.2 py27_0
        - sqlite 3.26.0 h0c8e037_0
        - vc 9 h7299396_1
        - vs2008_runtime 9.00.30729.1 hfaea7d5_1
        - wheel 0.32.3 py27_0
        - wincertstore 0.2 py27hf04cefb_0
    run:
        - certifi >=2017.4.17
        - chardet >=3.0.2,<3.1.0
        - idna >=2.5,<2.9
        - python >=2.7,<2.8.0a0
        - urllib3 >=1.21.1,<1.25
test:
    imports:
        - requests
about:
    description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

        consumption.

        '
    dev_url: https://github.com/kennethreitz/requests
    doc_source_url: https://github.com/requests/requests/tree/master/docs
    doc_url: http://docs.python-requests.org/
    home: http://python-requests.org
    license: Apache 2.0
    license_file: LICENSE
    summary: Python HTTP for Humans
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carlodri
        - jakirkham
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - sigmavirus24
