# This file created by conda-build 3.0.27
# ------------------------------------------------

package:
    name: vc
    version: '9'
build:
    noarch: false
    number: '1'
    string: h7299396_1
    track_features:
        - vc9
requirements:
    run:
        - vs2008_runtime >=9.0.30729.1,<10.0a0
about:
    description: 'This metapackage is used to activate vc features without

        depending on Python.

        '
    dev_url: https://github.com/conda/conda/wiki/VC-features
    doc_url: https://github.com/conda/conda/wiki/VC-features
    home: https://github.com/conda/conda/wiki/VC-features
    license: Modified BSD License (3-clause)
    license_family: BSD
    summary: A meta-package to track VC features.
extra:
    copy_test_source_files: true
    final: true
    parent_recipe:
        name: vs2008
        path: C:\ci\containers\000036g4uec\tmp\build\80754af9\rsync-recipes\vs2008-9.00.30729.1-on-winbuilder
        version: 9.00.30729.1
