# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00000pdpak7\tmp\build\80754af9\rsync-recipes\certifi-2019.3.9-python_2.7-on-winbuilder, last modified Mon Mar 11 10:28:01 2019
# ------------------------------------------------

package:
    name: certifi
    version: 2019.3.9
source:
    sha256: b26104d6835d1f5e49452a26eb2ff87fe7090b89dfcaee5ea2212697e1e1d7ae
    url: https://pypi.io/packages/source/c/certifi/certifi-2019.3.9.tar.gz
build:
    number: '0'
    preserve_egg_dir: true
    script: python setup.py install
    string: py27_0
requirements:
    host:
        - python 2.7.15 hcb6e200_15
        - sqlite 3.26.0 h0c8e037_0
        - vc 9 h7299396_1
        - vs2008_runtime 9.00.30729.1 hfaea7d5_1
    run:
        - python >=2.7,<2.8.0a0
test:
    imports:
        - certifi
about:
    description: 'Certifi is a curated collection of Root Certificates for validating
        the

        trustworthiness of SSL certificates while verifying the identity of TLS

        hosts.

        '
    dev_url: https://github.com/certifi/python-certifi
    doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/certifi
    home: http://certifi.io/
    license: ISC
    license_file: LICENSE
    summary: Python package for providing Mozilla's CA Bundle.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - ocefpaf
        - pelson
        - sigmavirus24
