# This file created by conda-build 3.0.21+2.gd8f972ad5
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\wincertstore-feedstock\recipe, last modified Tue Sep 19 10:23:23 2017
# ------------------------------------------------

package:
    name: wincertstore
    version: '0.2'
source:
    fn: wincertstore-0.2.zip
    sha256: 780bd1557c9185c15d9f4221ea7f905cb20b93f7151ca8ccaed9714dce4b327a
    url: https://pypi.io/packages/source/w/wincertstore/wincertstore-0.2.zip
build:
    number: '0'
    script: python setup.py install
    string: py27hf04cefb_0
requirements:
    build:
        - python 2.7.13 hb034564_12
        - vc 9 h7299396_0
        - vs2008_runtime 9.00.30729.1 hfaea7d5_0
    host:
        - python 2.7.13 hb034564_12
        - vc 9 h7299396_0
        - vs2008_runtime 9.00.30729.1 hfaea7d5_0
    run:
        - python >=2.7,<2.8.0a0
test:
    imports:
        - wincertstore
about:
    home: https://bitbucket.org/tiran/wincertstore
    license: PSF 2
    license_file: LICENSE
    summary: Python module to extract CA and CRL certs from Windows' cert store (ctypes
        based).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - patricksnape
