# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001s41ol0\tmp\build\80754af9\rsync-recipes\pip-19.0.3-python_2.7-on-winbuilder, last modified Mon Feb 25 15:13:44 2019
# ------------------------------------------------

package:
    name: pip
    version: 19.0.3
source:
    sha256: 6e6f197a1abfb45118dbb878b5c859a0edbdd33fd250100bc015b67fded4b9f2
    url: https://pypi.io/packages/source/p/pip/pip-19.0.3.tar.gz
build:
    disable_pip: true
    entry_points:
        - pip = pip._internal:main
    number: '0'
    string: py27_0
requirements:
    host:
        - certifi 2018.11.29 py27_0
        - python 2.7.15 hcb6e200_15
        - setuptools 40.8.0 py27_0
        - sqlite 3.26.0 h0c8e037_0
        - vc 9 h7299396_1
        - vs2008_runtime 9.00.30729.1 hfaea7d5_1
        - wincertstore 0.2 py27hf04cefb_0
    run:
        - python >=2.7,<2.8.0a0
        - setuptools
        - wheel
test:
    commands:
        - pip -h
        - pip list
    imports:
        - pip
about:
    dev_url: https://github.com/pypa/pip
    doc_url: https://pip.pypa.io/en/stable/
    home: https://pip.pypa.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: PyPA recommended tool for installing Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
