# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\enum34-feedstock\recipe, last modified Tue Jul  3 15:47:05 2018
# ------------------------------------------------

package:
    name: enum34
    version: 1.1.6
source:
    fn: enum34-1.1.6.tar.gz
    sha256: 8ad8c4783bf61ded74527bffb48ed9b54166685e4230386a9ed9b1279e2df5b1
    url: https://pypi.io/packages/source/e/enum34/enum34-1.1.6.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py27_1
requirements:
    host:
        - certifi 2018.4.16 py27_0
        - python 2.7.15 he216670_0
        - setuptools 39.2.0 py27_0
        - vc 9 h7299396_1
        - vs2008_runtime 9.00.30729.1 hfaea7d5_1
        - wincertstore 0.2 py27hf04cefb_0
    run:
        - python >=2.7,<2.8.0a0
test:
    imports:
        - enum
about:
    description: 'enumeration is a set of symbolic names bound to unique, constant
        values.

        Within it, the members can be compared by identity and the enumeration

        itself can be iterated over.

        '
    dev_url: https://bitbucket.org/stoneleaf/enum34
    doc_source_url: https://bitbucket.org/stoneleaf/enum34/src/default/enum/doc/enum.rst
    doc_url: https://pypi.python.org/pypi/enum34
    home: https://bitbucket.org/stoneleaf/enum34
    license: BSD 3-Clause
    summary: Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
