# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000029cv556\tmp\build\80754af9\rsync-recipes\cryptography-2.6.1-python_2.7-c_compiler_vs2008-on-winbuilder, last modified Mon Mar 11 08:39:05 2019
# ------------------------------------------------

package:
    name: cryptography
    version: 2.6.1
source:
    patches:
        - 0001-Skip-macOS-test-for-getentropy.patch
    sha256: 26c821cbeb683facb966045e2064303029d572a87ee69ca5a1bf54bf55f93ca6
    url: https://pypi.io/packages/source/c/cryptography/cryptography-2.6.1.tar.gz
build:
    number: '0'
    script:
        - if "%openssl%" == "1.0.2" set CRYPTOGRAPHY_WINDOWS_LINK_LEGACY_OPENSSL=1
        - python -m pip install --no-deps --ignore-installed . -vv
    string: py27hcfb25f9_0
requirements:
    build:
        - vs2008_win-64 9.00.30729.1 hb7fc0b5_1
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2018.11.29 py27_0
        - cffi 1.12.1 py27hcfb25f9_0
        - openssl 1.1.1b h0c8e037_1
        - pip 19.0.3 py27_0
        - pycparser 2.19 py27_0
        - python 2.7.15 hcb6e200_15
        - setuptools 40.8.0 py27_0
        - sqlite 3.26.0 h0c8e037_0
        - vc 9 h7299396_1
        - vs2008_runtime 9.00.30729.1 hfaea7d5_1
        - wheel 0.33.1 py27_0
        - wincertstore 0.2 py27hf04cefb_0
    run:
        - asn1crypto >=0.21.0
        - cffi >=1.7
        - enum34
        - idna >=2.1
        - ipaddress
        - openssl >=1.1.1b,<1.1.2a
        - python >=2.7,<2.8.0a0
        - six >=1.4.1
        - vc 9.*
test:
    commands:
        - pytest
    imports:
        - cryptography
        - cryptography.fernet
        - cryptography.hazmat
        - cryptography.hazmat.backends
        - cryptography.hazmat.backends.openssl
        - cryptography.hazmat.bindings
        - cryptography.hazmat.bindings.openssl
        - cryptography.hazmat.primitives
        - cryptography.hazmat.primitives.asymmetric
        - cryptography.hazmat.primitives.ciphers
        - cryptography.hazmat.primitives.kdf
        - cryptography.hazmat.primitives.twofactor
        - cryptography.x509
        - cryptography.x509.certificate_transparency
    requires:
        - cryptography-vectors 2.6.1.*
        - hypothesis >=1.11.4
        - iso8601
        - pretend
        - pytest >=3.2.1,!=3.3.0
        - pytz
    source_files:
        - tests
about:
    description: 'Cryptography is a package which provides cryptographic recipes and

        primitives to Python developers. Our goal is for it to be your

        "cryptographic standard library". It supports Python 2.6-2.7, Python 3.3+,

        and PyPy 2.6+. Cryptography includes both high level recipes, and low level

        interfaces to common cryptographic algorithms such as symmetric ciphers,

        message digests and key derivation functions.

        '
    dev_url: https://github.com/pyca/cryptography
    doc_source_url: https://github.com/pyca/cryptography/tree/master/docs
    doc_url: http://cryptography.readthedocs.io/
    home: https://github.com/pyca/cryptography
    license: Apache 2.0 or BSD 3-Clause, PSF 2
    license_family: BSD
    license_file: LICENSE
    summary: Provides cryptographic recipes and primitives to Python developers
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jschueller
        - ocefpaf
